apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
      - name: airflow
        image: apache/airflow:2.4.1
        envFrom:
        - configMapRef:
            name: airflow-config
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /opt/airflow/dags
          name: airflow-dags
        - mountPath: /opt/airflow/logs
          name: airflow-logs
      volumes:
      - name: airflow-dags
        persistentVolumeClaim:
          claimName: airflow-pvc
      - name: airflow-logs
        persistentVolumeClaim:
          claimName: airflow-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: airflow
  namespace: airflow
spec:
  ports:
    - port: 8080
  selector:
    app: airflow
